INCLUDE(${OE_CURRENT_EXTENSION_DIR}/FindLibVNCServer.cmake)

IF (LIBVNCSERVER_FOUND) 
  INCLUDE_DIRECTORIES(${LIBVNCSERVER_INCLUDE_DIR})
ELSE (LIBVNCSERVER_FOUND)
  MESSAGE ("WARNING: Could not find LibVNCServer - depending targets will be disabled.")
ENDIF (LIBVNCSERVER_FOUND)

